### ISSUE TITLE
Search results page / upload form: Implement revised terms under "Participant type" and "Age of learners"

### ISSUE THREAD

**Issue by RKasprowicz** [digital-york/oasis#45]
Implement revised terms under metadata field "Participant type". Implement separate multiple choice field "Age of learners" (revise existing "Age of learners" field, which currently is an open text field).

See [Updated_OASIS Search terms](https://docs.google.com/spreadsheets/d/1rGBsH857eKLQgozQR_pAzROjZtFl-e2Jd3jcwojekSo/edit?usp=sharing) spreadsheet for revised terms

**Comment by yf508** [comment]
done.

**Comment by paluchas** [comment]
Reopen till testing not finished.

**Comment by RKasprowicz** [comment]
@paluchas @yf508 There are outstanding issues here, as below:

1. The term "Teacher educator / CPD provider" needs to be added to the "Participant type" metadata field and the "Participant type" search field on the search results page.

2. The following terms need to be removed from the "Participant type" metadata field in the upload form and removed from the "Participant type" search field on the search results page:
- adolescent learners
- adult learners
- primary school
- secondary school
- young learners

3. The metadata field "Age of learners" is incorrectly labelled as "Gender of learners". Please can name of field to "Age of learners" and the description text to "Age of learners involved in this research study"

![image](https://user-images.githubusercontent.com/36402489/37089893-3113b564-21fa-11e8-934d-c9a88ec538d3.png)

4. The search terms under the facet "Age of learners" on the Search results page should be the same as the checkbox options available on the upload form for Age of learners (Young learners, Adolescent learners, Adult learners). At the moment, the search terms available here reflect the old information entered when "Age of learners" was a free text entry box.
![image](https://user-images.githubusercontent.com/36402489/37089979-7d46d4e8-21fa-11e8-8316-0ec6d8cb9e8d.png)

**Comment by SophieThompson** [comment]
@paluchas @RKasprowicz I have deleted old summaries and made a new one and the "age of learner" issue still exists. It doesn't appear in the summary detail page or in the search results, and in the drop down search facets the old values still show (images below)

![image](https://user-images.githubusercontent.com/36706240/37297139-e4c26f92-2614-11e8-9d28-69e8de9e7c4a.png)

![image](https://user-images.githubusercontent.com/36706240/37297156-e913422e-2614-11e8-8bd3-56a1b8a766fe.png)

![image](https://user-images.githubusercontent.com/36706240/37297162-eac8bed2-2614-11e8-9578-3a12bdb6bfa3.png)

**Comment by paluchas** [comment]
@SophieThompson  Age of learners should show correctly on demo now

**Comment by RKasprowicz** [comment]
@paluchas @SophieThompson Age of learners is now showing correctly in search facet list, search results page and summary detailed view.
